# Generated by Django 6.0.2 on 2026-06-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('AI', 'AI & Machine Learning'), ('TECH', 'Technical'), ('CULT', 'Cultural'), ('SPRT', 'Sports'), ('EDUC', 'Education')], default='TECH', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('AI', 'Artificial Intelligence'), ('IT', 'Information Technology'), ('CS', 'Computer Science'), ('BE', 'Business Engineering'), ('EDUC', 'Education')], max_length=50, null=True),
        ),
    ]
